### ISSUE TITLE
Falta el reporte de Testing Falta documentación. Faltan tests

### ISSUE THREAD

**Issue by josejesusguzman** [Jonhy-D/hub-entertainment-mega#1]
Falta el reporte de Testing
Falta documentación. Faltan tests

**Comment by Jonhy-D** [comment]
Hola Jesús,
Según yo tenia toda la documentación y el testing pero tal vez no a la manera que querias, no se si podrías decirme si ahora si podría pasar el sprint 2 y 3 o que me falta?
